### PR TITLE
BlocPresentationListener has dynamic type argument

### LINKED ISSUE #8: Issue with generic typing in  BlocPresentationListener
I want to use this package, but one thing is not working as expected. 

Suppose you want to create some "base" bloc where each bloc should extend in - for example provide some "logging" common method etc. 

```dart
abstract class SafeBlocBase<STATE> extends BlocBase<STATE> BlocPresentationMixin<STATE> {
  SafeBlocBase(super.state);

// .. common methods,...
}
```

Now suppose we want also create generic widget with `BlocPresentationListener`

```dart
class UnexpectedErrorHandler<BLOC extends SafeBlocBase<STATE>, STATE> extends StatelessWidget {
  final Widget child;  

  // constructor ommitted

  @override
  Widget build(BuildContext context) {
    final cubit = context.watch<BLOC?>();

    if (cubit == null) return child;

    return BlocPresentationListener<BLOC>(
      listener: (context, effect) async {
         // do something
      },
      child: child,     
    );
  }
}
```
**Issue is** that BlocPresentationMixin is defined as 

```dart
BlocPresentationMixin<S> on BlocBase<S>
```
which is expected - mixing should be bound to BlocBase with concrete State "S". 

However `BlocPresentationListener` is defined as 

```dart
class BlocPresentationListener<B extends BlocPresentationMixin<Object>>
```

This leads to compilation error  in our `UnexpectedErrorHandler` 

```
'BLOC' doesn't conform to the bound 'BlocPresentationMixin<Object>' of the type parameter 'B'.
Try using a type that is or is a subclass of 'BlocPresentationMixin<Object>'
```

### What I've tried 

Define SafeBlocBase with mixin BlocPresentationMixin<Object> -> does not conform 
```
'SafeBlocBaseMixin<Object>' can't be mixed onto 'BlocBase<STATE>' because 'BlocBase<STATE>' doesn't implement 'BlocBase<Object>'.
Try extending the class 'SafeBlocBaseMixin<Object>'.
```

## Proposal
Cleanest way is to define BlocPresentationListener with state type S which is bounded with mixin of same type

```dart
class BlocPresentationListener<S, B extends BlocPresentationMixin<S>>
```

or change Object to dynamic which works too

```dart
class BlocPresentationListener<B extends BlocPresentationMixin<dynamic>> 
```

I will create PR if you agree that this should be changed.

### PR DESCRIPTION
**Pull request by petrnymsa**
Fixes #8

### CODE REVIEW

**Comment by shilangyu** [comment]
Thanks for the contribution! Could you run `dart format` on the new code?

**Comment by petrnymsa** [comment]
> Thanks for the contribution! Could you run `dart format` on the new code?

Done

**Comment by shilangyu** [comment]
Thanks for the contribution! I will make a release soon

**Comment by petrnymsa** [comment]
@shilangyu  Hey, thank you for quick merge, i am not sure if you are aware pub publish action failed, so new version on pub.dev is not available

**Comment by Albert221** [comment]
Blocked by https://github.com/leancodepl/mobile-tools/issues/38

**Comment by shilangyu** [comment]
@petrnymsa thanks, did not notice. It should be on pub now

**Pull request merged**
